# SPDX-License-Identifier: AGPL-3.0-or-later
"""The project steward's core memory (technical paper §5-b, phase 6).

The steward is a role plus a memory, not a model: whatever model the registry
assigns reads `<project>/.hydra/steward/core.md` first, so knowledge of the
project survives sessions, compactions and a change of model. The core memory
is short (about 2k tokens) and is read into every context pack and by the
manager at the start of a session; everything larger stays in the archive
(the repository map, lessons, skills, closing reports) and is retrieved on
demand.

`init` writes the facts a script can find (languages, layout, test and build
commands, the most central files by the repository map's ranking). The
sections only judgment can fill (architecture, invariants, conventions,
danger zones) start empty; the manager fills and updates them with
`steward set`, one recorded change at a time.
"""

import json
import re
import subprocess
from pathlib import Path

from . import ledger, repomap

SECTIONS = ("Architecture", "Invariants", "Conventions", "Danger zones")
GENERATED = "Facts (generated)"
MAX_CHARS = 8000          # ≈ 2k tokens
EVENT = "hydra/steward-changed"


def path(project) -> Path:
    return Path(project) / ".hydra" / "steward" / "core.md"


def _test_commands(project: Path) -> list[str]:
    out = []
    pkg = project / "package.json"
    if pkg.exists():
        try:
            scripts = json.loads(pkg.read_text()).get("scripts", {})
            out += [f"npm run {k}" for k in ("test", "build", "lint") if k in scripts]
        except ValueError:
            pass
    if (project / "pyproject.toml").exists() or (project / "tests").is_dir():
        if "pytest" in ((project / "pyproject.toml").read_text() if (project / "pyproject.toml").exists() else ""):
            out.append("python3 -m pytest")
        elif (project / "tests").is_dir():
            out.append("python3 -B -m unittest discover -s tests")
    mk = project / "Makefile"
    if mk.exists():
        out += [f"make {t}" for t in ("test", "build", "lint") if re.search(rf"^{t}:", mk.read_text(), re.M)]
    for script in ("scripts/test.sh", "test.sh"):
        if (project / script).exists():
            out.append(script)
    if (project / "Cargo.toml").exists():
        out.append("cargo test")
    if (project / "go.mod").exists():
        out.append("go test ./...")
    return out


def facts(project) -> str:
    project = Path(project)
    files = repomap.source_files(project)
    langs: dict[str, int] = {}
    tops: dict[str, int] = {}
    for f in files:
        langs[Path(f).suffix] = langs.get(Path(f).suffix, 0) + 1
        tops[f.split("/")[0] if "/" in f else "."] = tops.get(f.split("/")[0] if "/" in f else ".", 0) + 1
    idx = repomap.index(project)
    ranked = sorted(repomap.rank(idx).items(), key=lambda x: -x[1])[:8]
    head = subprocess.run(["git", "-C", str(project), "rev-parse", "--short", "HEAD"], capture_output=True,
                          text=True).stdout.strip() or "no commit"
    lines = [f"- At git {head}: {len(files)} source file(s): "
             + ", ".join(f"{n} {ext}" for ext, n in sorted(langs.items(), key=lambda x: -x[1])),
             "- Layout: " + ", ".join(f"{d}/ ({n})" if d != "." else f"root ({n})" for d, n in sorted(tops.items())),
             "- Test and build commands found: " + (", ".join(f"`{c}`" for c in _test_commands(project)) or "none"),
             "- Most central files (used by the most other files): "
             + ", ".join(f"`{f}`" for f, _ in ranked if idx[f]["defs"])]
    return "\n".join(lines)


def _render(sections: dict[str, str]) -> str:
    out = ["# Project steward: core memory", "",
           "Read this first. Facts are regenerated by `hydra-pod-dsh steward init`; the other sections are kept "
           "by the manager with `hydra-pod-dsh steward set`.", ""]
    for name in (GENERATED,) + SECTIONS:
        out += [f"## {name}", "", sections.get(name, "").strip() or "(not written yet)", ""]
    return "\n".join(out)


def read_sections(project) -> dict[str, str]:
    f = path(project)
    if not f.exists():
        return {}
    out, cur = {}, None
    for line in f.read_text().splitlines():
        m = re.match(r"^## (.+)$", line)
        if m:
            cur = m.group(1).strip()
            out[cur] = []
        elif cur:
            out[cur].append(line)
    return {k: "\n".join(v).strip() for k, v in out.items() if "\n".join(v).strip() != "(not written yet)"}


def init(project) -> Path:
    """Write (or refresh) the generated facts, keeping every section the manager wrote."""
    sections = read_sections(project)
    sections[GENERATED] = facts(project)
    f = path(project)
    f.parent.mkdir(parents=True, exist_ok=True)
    f.write_text(_render(sections))
    ledger.append(project, EVENT, workflow_id="STEWARD", actor={"kind": "tool"}, reason="facts regenerated",
                  ignorable=True, payload={"section": GENERATED})
    return f


def set_section(project, section: str, text: str, reason: str) -> Path:
    if section not in SECTIONS:
        raise ValueError(f"section must be one of {SECTIONS}")
    if not reason or not reason.strip():
        raise ValueError("a change to the steward's memory needs a reason")
    sections = read_sections(project)
    before = sections.get(section, "")
    sections[section] = text.strip()
    rendered = _render(sections)
    if len(rendered) > MAX_CHARS:
        raise ValueError(f"core memory would be {len(rendered)} characters (limit {MAX_CHARS}): "
                         "move detail to a skill or a lesson and keep only the rule here")
    f = path(project)
    f.parent.mkdir(parents=True, exist_ok=True)
    f.write_text(rendered)
    ledger.append(project, EVENT, workflow_id="STEWARD", actor={"kind": "manager"}, reason=reason, ignorable=True,
                  payload={"section": section, "before_chars": len(before), "after_chars": len(text.strip())})
    return f


def core(project) -> str | None:
    f = path(project)
    return f.read_text() if f.exists() else None
